name: xmark
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: ^0.20.1
  open_file: ^3.5.10
  path_provider: ^2.1.5
  pdf: ^3.11.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
