// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_trL3O6srylBiIZMFLfOohPj-rcVVW74',
    appId: '1:961645083255:web:d91a67ce8f8d0d05a8e472',
    messagingSenderId: '961645083255',
    projectId: 'xmark-13f80',
    authDomain: 'xmark-13f80.firebaseapp.com',
    storageBucket: 'xmark-13f80.firebasestorage.app',
    measurementId: 'G-VFCEKJ8EFC',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnhrsX_oKj_-METxYkKlrKuWPYlmp7gb0',
    appId: '1:961645083255:ios:5952869639853ddba8e472',
    messagingSenderId: '961645083255',
    projectId: 'xmark-13f80',
    storageBucket: 'xmark-13f80.firebasestorage.app',
    iosBundleId: 'com.example.xmark',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCfGBjZjTjN7bQZ0fJtVjnegnBbG56O6Y',
    appId: '1:961645083255:android:a13cf997109f2d32a8e472',
    messagingSenderId: '961645083255',
    projectId: 'xmark-13f80',
    storageBucket: 'xmark-13f80.firebasestorage.app',
  );

}